### ISSUE TITLE
Support repeating fixed column values - disallow filling

### ISSUE THREAD

**Issue by chriseth** [chriseth/powdr#114]
Support `[...]*` to repeat the contents of the array. Maybe also support `[...] + [...]` for concatenation.

Once we have that, we should disallow the auto-filling with zeros. We could also check that repetitions match the degree, repetitions do not end in the middle of a repetiton.

**Comment by Schaeff** [comment]
This can be closed?

**Comment by chriseth** [comment]
Implemented by #125
