### ISSUE TITLE
Refactor: Split EvalResult into more reasonable results

### ISSUE THREAD

**Issue by chriseth** [chriseth/powdr#158]
Evaluating a lookup/identity or a machine should return one of the following things:
 - constraint is fully satisfied, it is not possible to extract more information out of it (because all values are constants/known)
 - constraint is satisfied so far, and some new assignments could be extracted
 - constraint is satisfied so far, but there are variables that are still unknown
 - constraint is violated

**Comment by Schaeff** [comment]
So the first three are Ok and the last one is the only Err, correct?

**Comment by chriseth** [comment]
Yes. Actually a better distinction could be to turn the non-error case into a tuple:
`(Vec<Assignments>, bool)`, where the boolean indicates if there are still degrees of freedom in the query, i.e. if there are still unknown variables.
