### ISSUE TITLE
Machine extraction is not deterministic

### ISSUE THREAD

**Issue by chriseth** [chriseth/powdr#199]

**Comment by lvella** [comment]
`split_out_machines()` output `Vec`s order is non-deterministic due to a `HashSet`. Make them always return in the same order.

**Comment by lvella** [comment]
Looking at the code, it seems there are 2 places affected by the non-determinism:
- one log message;
- the position in `SortedWitnesses.witness_positions`.

Just sorting the iterator in those places should do the trick.
