### ISSUE TITLE
Translate riscv to powdr-asm

### ISSUE THREAD

**Issue by chriseth** [chriseth/powdr#80]
We could parse riscv assembly and translate it to a (minimally modified) powdr-asm. This way, random code can be verified using powdr - we could write an EVM interpreter in rust, compile it to riscv and verify the execution using powdr.

As reference: Simple simulator in rust https://github.com/GregAC/rrs

**Comment by leonardoalt** [comment]
This is done, isn't it?

**Comment by chriseth** [comment]
I would close it as soon as we have #212

**Comment by lvella** [comment]
We have #212, closing.
